### ISSUE TITLE
Ligatures are broken on Shell Script filetype

### ISSUE THREAD

**Issue by daenney** [nordtheme/visual-studio-code#168] opened 2020-01-22 14:03 UTC
- VSCode Version: 1.41.1
- Nord plugin version: 0.13.0
- OS Version: Linux monoceros 5.4.8-arch1-1

Steps to Reproduce:

1. Use a font like Fira Code or JetBrains Mono that supports ligatures: `"editor.fontFamily": "JetBrains Mono"`
2. Enable ligatures in the editor: `"editor.fontLigatures": true`
3. Open up a file who's type gets mapped to/detected as Shell Script
4. Try a sequence of characters that should render as a ligature, like `!=` which should render as `≠`

When I disable the Nord extension, the issue goes away and ligatures render properly. The issue also goes away if I change the file type to plain, which seems to disable Nord's syntax highlighting entirely.

This doesn't affect all file types, for example ligatures are rendered correctly when editing `.go` files.

**Comment by arcticicestudio** [comment] 2020-01-23 09:39
Hi @daenney :wave:, thanks for your contribution :+1:

**Comment by arcticicestudio** [comment] 2020-01-23 15:29
Hi @daenney :wave:, thanks for your contribution :+1:
This sounds a like a strange behavior. Nord doesn't define any specific styles for shell scripts. There is also no way for themes to modify, set or recommend a specific font family to be used with the theme.

I tried to reproduce the problem, but it works fine at least on macOS, but this shouldn't affect the rendering in VS Code in any way. I've used [Fira Code][fc] instead of the new _JetBrains Mono_ font, so maybe it's a problem with the don't family itself or the package for Arch is not properly created.

<p align="center">With <strong>disabled</strong> ligatures using <em>Fira Code</em> font</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/72974137-d25ba480-3dce-11ea-8600-747c6dcb4aa4.png" /></p>

<p align="center">With <strong>enabled</strong> ligatures using <em>Fira Code</em> font</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/72974139-d25ba480-3dce-11ea-90a1-d0fee47b220f.png" /></p>

Can you please try if the problem is still reproducible with other themes like a builtin theme or custom one?

[fc]: https://github.com/tonsky/FiraCode

**Comment by arcticicestudio** [comment] 2020-06-16 18:46
@daenney Have you been able to fix the problem or reproduce it with other themes?

**Comment by daenney** [comment] 2020-06-20 12:13
I can reproduce it on some themes:

* Light, Light+, Dark, Dark+, Kimbie Dark, ligatures work as expected in shell files
* Quiet Light, Solarized Light, Abyss, Monokai, Monokai Dimmed, Red, Solarized Dark, Tomorrow Night Blue, High Contrast: ligatures don't work in shell files

**Comment by arcticicestudio** [comment] 2020-06-20 12:53
Thanks for testing, so this definitely sounds like a bug in VSCode itself. Could you please [open an issue in their repository](https://github.com/microsoft/vscode/issues/new/choose) so they can check this? Feel free to reference this issue, I guess it might help to reproduce the problem.

**Comment by svengreb** [comment] 2023-07-16 09:13
Thank you for your patience! 🙏🏼
It‘s been a while [since I had free time to focus more on Nord, and my open source projects in general](https://github.com/orgs/nordtheme/discussions/183#user-content-todays-scope), and invest time in this issue due to [work-life balance](https://github.com/orgs/nordtheme/discussions/183#work-life-balance).

I recently published the first [“Northern Post — The state and roadmap of Nord“ announcement](https://github.com/orgs/nordtheme/discussions/183) which includes all details about the plans and future of the _Nord_ project, including [the goal of catching up with the backlog](https://github.com/orgs/nordtheme/discussions/183#catching-up-on-the-backlog). This issue is part of the backlog and therefore I want to triage and process it to get one step closer to a “clean state“. Read the [announcement about reaching the “clean“ contribution triage state](https://github.com/orgs/nordtheme/discussions/202) in Nord‘s discussions for more details about the goal.

Therefore it has been added to [the central and _single-source-of-truth_ project board](https://github.com/orgs/nordtheme/projects/1) [^1] that is also [described in more detail in the roadmap announcement](https://github.com/orgs/nordtheme/discussions/183#with-central-project-planning-and-issue-management).

---

@daenney Thanks again for your contributions 🚀
Since [the bug was fixed upstream](https://github.com/microsoft/vscode/issues/100649#issuecomment-741637720) I‘ll close this issue as resolved.

[^1]: https://github.com/orgs/nordtheme/projects/1/views/7?pane=issue&itemId=33378050

**Closed by svengreb** 2023-07-16 09:13 UTC
Labels: context-syntax, scope-compatibility
